[package]
name = "snake_rust"
version = "0.1.0"
authors = ["poliv"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
getrandom = "0.2.2"
oorandom = "11.1.3"
